{% set name = "runthis-sphinxext" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}
  version: {{ version }}

build:
  noarch: python
  number: {{ build_number }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx

test:
  imports:
    - runthis_sphinxext
  commands:
    - pytest
  requires:
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/regro/runthis-sphinxext
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
